### ISSUE TITLE
ccxt.base.errors.InvalidOrder: binance

### ISSUE THREAD

**Issue by alantucker** [hackingthemarkets/gridbot-websockets#2]
Just to let you know that when using the Binance exchange I get the following error:

`ccxt.base.errors.InvalidOrder: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

**Comment by anurag-oxf** [comment]
This is prolly cause on binance, minimum order size per transaction is $10 USDT .. So if you are passing something less than $10, i think thats where this error comes from. Try a bigger size position >$10 USDT

**Comment by alantucker** [comment]
Yeah, I have been playing some more with the code and up'ed my account. I also had to change the order id from 'id' to 'orderId'
